# Generated by Django 5.0.6 on 2024-06-22 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNumber', models.IntegerField()),
                ('SecondNumber', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 14, 36, 42, 876699))),
            ],
        ),
    ]
