# Generated by Django 5.0.6 on 2024-06-22 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNumber', models.IntegerField()),
                ('SecondNumber', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 15, 26, 52, 978462))),
            ],
        ),
        migrations.CreateModel(
            name='mulm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNumber', models.IntegerField()),
                ('SecondNumber', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 15, 26, 52, 978462))),
            ],
        ),
        migrations.CreateModel(
            name='quom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNumber', models.IntegerField()),
                ('SecondNumber', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 15, 26, 52, 978462))),
            ],
        ),
        migrations.CreateModel(
            name='remm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNumber', models.IntegerField()),
                ('SecondNumber', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 15, 26, 52, 978462))),
            ],
        ),
        migrations.CreateModel(
            name='subm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstNumber', models.IntegerField()),
                ('SecondNumber', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 22, 15, 26, 52, 978462))),
            ],
        ),
        migrations.AlterField(
            model_name='addm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 15, 26, 52, 978462)),
        ),
    ]
