# Generated by Django 5.0.6 on 2024-06-24 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expm_mulm_quom_remm_subm_alter_addm_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='primem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 24, 13, 44, 18, 260922))),
            ],
        ),
        migrations.AlterField(
            model_name='addm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 13, 44, 18, 245299)),
        ),
        migrations.AlterField(
            model_name='expm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 13, 44, 18, 245299)),
        ),
        migrations.AlterField(
            model_name='mulm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 13, 44, 18, 245299)),
        ),
        migrations.AlterField(
            model_name='quom',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 13, 44, 18, 245299)),
        ),
        migrations.AlterField(
            model_name='remm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 13, 44, 18, 245299)),
        ),
        migrations.AlterField(
            model_name='subm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 13, 44, 18, 245299)),
        ),
    ]
