# Generated by Django 5.0.6 on 2024-06-25 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_addm_time_alter_expm_time_alter_mulm_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547))),
            ],
        ),
        migrations.AlterField(
            model_name='addm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547)),
        ),
        migrations.AlterField(
            model_name='expm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547)),
        ),
        migrations.AlterField(
            model_name='mulm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547)),
        ),
        migrations.AlterField(
            model_name='primem',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547)),
        ),
        migrations.AlterField(
            model_name='quom',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547)),
        ),
        migrations.AlterField(
            model_name='remm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547)),
        ),
        migrations.AlterField(
            model_name='subm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 22, 30, 38, 363547)),
        ),
    ]
