# Generated by Django 5.0.6 on 2024-07-02 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_addm_time_alter_cbrtm_time_alter_expm_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addm',
            name='FirstNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addm',
            name='SecondNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='addm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='cbrtm',
            name='Number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cbrtm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='expm',
            name='FirstNumber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='expm',
            name='SecondNumber',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='expm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='facm',
            name='Number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='facm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='fibm',
            name='Number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='fibm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='mulm',
            name='FirstNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mulm',
            name='SecondNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mulm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='otpm',
            name='Number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='otpm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='primem',
            name='Number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='primem',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='quom',
            name='FirstNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quom',
            name='SecondNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quom',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='remm',
            name='FirstNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='remm',
            name='SecondNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='remm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='sqrtm',
            name='Number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sqrtm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
        migrations.AlterField(
            model_name='subm',
            name='FirstNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subm',
            name='SecondNumber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 18, 24, 40, 64845)),
        ),
    ]
