# Generated by Django 5.0.6 on 2024-07-02 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_addm_time_alter_cbrtm_time_alter_expm_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='milem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.FloatField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194))),
            ],
        ),
        migrations.AlterField(
            model_name='addm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 524571)),
        ),
        migrations.AlterField(
            model_name='cbrtm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='expm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='facm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='fibm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='mulm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 524571)),
        ),
        migrations.AlterField(
            model_name='otpm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='primem',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='quom',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='remm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='sqrtm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 540194)),
        ),
        migrations.AlterField(
            model_name='subm',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 19, 4, 21, 524571)),
        ),
    ]
